FROM netboxcommunity/netbox:v4.4.8
# 如果想尝试最新版，使用latest版本构建镜像
#FROM netboxcommunity/netbox:latest

COPY ./plugin_requirements.txt /opt/netbox/
RUN /usr/local/bin/uv pip install -r /opt/netbox/plugin_requirements.txt

# These lines are only required if your plugin has its own static files.
COPY configuration/configuration.py /etc/netbox/config/configuration.py
COPY configuration/plugins.py /etc/netbox/config/plugins.py
RUN DEBUG="true" SECRET_KEY="dummydummydummydummydummydummydummydummydummydummy" \
    /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py collectstatic --no-input

# 解决 Netbox 导出 CSV 文件中文乱码问题
RUN sed -i 's|CSV: "text/csv; charset=utf-8",|CSV: "text/csv; charset=utf-8-sig",|' \
    /opt/netbox/venv/lib/python*/site-packages/django_tables2/export/export.py